### ISSUE TITLE
inactive Airdrop

### ISSUE THREAD

**Issue by mehmetyukcell** [a565109863/AirPortOpenBSD#1]
Thanks for your works, airdrop inactive shows with AirPortOpenBSD.kext, but works with airportitlwm (only device is scanning but not sending files).

**Comment by mehmetyukcell** [comment]
I used with EFI/OC/KEXTS opencore

**Comment by bh1044501616** [comment]
How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
I tried to add the AirportOpenBSD to the open core kernel list, but did't work.

**Comment by a565109863** [comment]
> How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> I tried to add the AirportOpenBSD to the open core kernel list, but did't work.

You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC

**Comment by mehmetyukcell** [comment]
So will airdrop work this way?

**Comment by a565109863** [comment]
> So will airdrop work this way?

no, wifi can work, but airdrop don't work.the kext only can work for wifi.

**Comment by laihenyi** [comment]
> IO80211Family.kext

in big sur , the same setting , right ? Actually , I did not find IO80211Family.kext in EFI folder ....

**Comment by laihenyi** [comment]
> > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> 
> You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC

in big sur , the same setting , right ? Actually , I did not find IO80211Family.kext in EFI folder ....

**Comment by ske1996** [comment]
> > > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> 
> > > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> 
> > 
> 
> > You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC
> 
> 
> 
> in big sur , the same setting , right ? Actually , I did not find IO80211Family.kext in EFI folder ....
> 
> 
> 
> 


1.You can find IO80211Family.kext at s/l/e which is in system directory

2.If my memory is not wrong,you can use it directly with laster than v0.6.3 of opencore,so upgrade your opencore to 0.6.4 is what i recammand

**Comment by mehmetyukcell** [comment]
> > > > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> > 
> > 
> > > > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> > 
> > 
> > > 
> > 
> > 
> > > You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC
> > 
> > 
> > in big sur , the same setting , right ? Actually , I did not find IO80211Family.kext in EFI folder ....
> 
> 1.You can find IO80211Family.kext at s/l/e which is in system directory
> 
> 2.If my memory is not wrong,you can use it directly with laster than v0.6.3 of opencore,so upgrade your opencore to 0.6.4 is what i recammand

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha the kext should be using with OC/Kexts and config kernel

**Comment by mehmetyukcell** [comment]
> > > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> > > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> > 
> > 
> > You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC
> 
> in big sur , the same setting , right ? Actually , I did not find IO80211Family.kext in EFI folder ....

https://github.com/OpenIntelWireless/itlwm/releases/tag/v1.2.0-alpha

**Comment by laihenyi** [comment]
> > > > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> > 
> > 
> > > > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> > 
> > 
> > > 
> > 
> > 
> > > You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC
> > 
> > 
> > in big sur , the same setting , right ? Actually , I did not find IO80211Family.kext in EFI folder ....
> 
> 1.You can find IO80211Family.kext at s/l/e which is in system directory
> 
> 2.If my memory is not wrong,you can use it directly with laster than v0.6.3 of opencore,so upgrade your opencore to 0.6.4 is what i recammand

Thank you !
I just found that in OC 0.6.4 , I can use AirportOpenBSD.kext without  IO80211Family.kext.

**Comment by bh1044501616** [comment]
> > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> 
> You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC

Isn't a risk if I move the AirportOpenBSD.kext into IO80211Family?
Is there any other solution?

**Comment by a565109863** [comment]
> > > How do I use the kerne with open core 0.5.6 and Mac OS X 10.14.6?
> > > I tried to add the AirportOpenBSD to the open core kernel list, but did't work.
> > 
> > 
> > You must move the AirportOpenBSD.kext into IO80211Family.kext/Contents/PlugIns,then add the AirportOpenBSD.kext and IO80211Family.kext into config file of OC
> 
> Isn't a risk if I move the AirportOpenBSD.kext into IO80211Family?
> Is there any other solution?

You should upgrade oc to the latest version
