### ISSUE TITLE
会导致mac无法启动，系统报错如下

### ISSUE THREAD

**Issue by olenzhang** [a565109863/AirPortOpenBSD#2]
panic(cpu 0 caller 0xffffff8001ded0e6): Kernel trap at 0xffffff8005a52fec, type 14=page fault, registers:
CR0: 0x000000008001003b, CR2: 0x0000000000000028, CR3: 0x000000000a417000, CR4: 0x00000000003626e0
RAX: 0xffffff86b4923000, RBX: 0xffffff86a34ec000, RCX: 0x0000000000000000, RDX: 0xffffff800242993c
RSP: 0xffffffa075e73c30, RBP: 0xffffffa075e73c60, RSI: 0x0000000000008000, RDI: 0xffffff86b4923000
R8:  0xffffff9363b55e70, R9:  0x0000000000008000, R10: 0x0000000016044000, R11: 0x0000000000000208
R12: 0xffffff8005a50fd0, R13: 0xffffff9362c284e0, R14: 0x0000000000000000, R15: 0xffffff9362c284e0
RFL: 0x0000000000010282, RIP: 0xffffff8005a52fec, CS:  0x0000000000000008, SS:  0x0000000000000010
Fault CR2: 0x0000000000000028, Error code: 0x0000000000000002, Fault CPU: 0x0, PL: 0, VF: 1

Backtrace (CPU 0), Frame : Return Address
0xffffffa075e73650 : 0xffffff8001cb9aed 
0xffffffa075e736a0 : 0xffffff8001dfc6e3 
0xffffffa075e736e0 : 0xffffff8001decd1a 
0xffffffa075e73730 : 0xffffff8001c5ea2f 
0xffffffa075e73750 : 0xffffff8001cb938d 
0xffffffa075e73870 : 0xffffff8001cb9678 
0xffffffa075e738e0 : 0xffffff80024be3ca 
0xffffffa075e73950 : 0xffffff8001ded0e6 
0xffffffa075e73ad0 : 0xffffff8001decdcd 
0xffffffa075e73b20 : 0xffffff8001c5ea2f 
0xffffffa075e73b40 : 0xffffff8005a52fec 
0xffffffa075e73c60 : 0xffffff8005abdaed 
0xffffffa075e73cc0 : 0xffffff8005abd9e1 
0xffffffa075e73d00 : 0xffffff8005abe148 
0xffffffa075e73d50 : 0xffffff8005abeb9d 
0xffffffa075e73da0 : 0xffffff8005ac41cb 
0xffffffa075e73de0 : 0xffffff8005ac4405 
0xffffffa075e73e10 : 0xffffff8005ac46a6 
0xffffffa075e73e40 : 0xffffff8005ac4772 
0xffffffa075e73e90 : 0xffffff8005acc872 
0xffffffa075e73ed0 : 0xffffff8005acbd18 
0xffffffa075e73f10 : 0xffffff8005ad0caa 
0xffffffa075e73f50 : 0xffffff8005a510bf 
0xffffffa075e73fa0 : 0xffffff8001c5e13e 
      Kernel Extensions in backtrace:
         com.zhong.AirPortOpenBSD(1.0)[50B2C3F5-E113-36A5-84F8-F59371BE4DA5]@0xffffff8005a0e000->0xffffff8007e44fff
            dependency: com.apple.iokit.IO80211Family(1200.12.2b1)[ABB341FB-8D9E-344D-8032-AFB070B29023]@0xffffff800363f000->0xffffff8003778fff
            dependency: com.apple.iokit.IONetworkingFamily(3.4)[9178A2AA-EFFD-3DA3-86C3-08EFD4DAF005]@0xffffff8004393000->0xffffff80043a9fff
            dependency: com.apple.iokit.IOPCIFamily(2.9)[D0F1BFB8-C28E-3E70-891B-73B783189394]@0xffffff800462c000->0xffffff8004653fff

Process name corresponding to current thread: kernel_task
Boot args: alcid=1 alcdelay=500 chunklist-security-epoch=0 -chunklist-no-rev2-dev

Mac OS version:
20C69

Kernel version:
Darwin Kernel Version 20.2.0: Wed Dec  2 20:39:59 PST 2020; root:xnu-7195.60.75~1/RELEASE_X86_64
Kernel UUID: 82E2050C-5936-3D24-AD3B-EC4EC5C09E11
KernelCache slide: 0x0000000001a00000
KernelCache base:  0xffffff8001c00000
Kernel slide:      0x0000000001a10000
Kernel text base:  0xffffff8001c10000
__HIB  text base: 0xffffff8001b00000
System model name: iMac20,1 (Mac-CFF7D910A743CAAF)
System shutdown begun: NO
Panic diags file available: YES (0x0)
Hibernation exit count: 0

System uptime in nanoseconds: 277257569393
Last Sleep:           absolute           base_tsc          base_nano
  Uptime  : 0x000000408dd6c68b
  Sleep   : 0x0000000000000000 0x0000000000000000 0x0000000000000000
  Wake    : 0x0000000000000000 0x00000013f31553fa 0x0000000000000000

**Comment by a565109863** [comment]
哪个型号的网卡

**Comment by olenzhang** [comment]
AX200
