### ISSUE TITLE
和itlwm有啥区别

### ISSUE THREAD

**Issue by sun19970908** [a565109863/AirPortOpenBSD#3]
这么老大

**Comment by Sn0wGZ** [comment]
感谢作者！详细对比过，下载速度比itIwm慢点，上载速度比itIwm快挺多，整体稳定性比itIwm强。希望能修复以下问题：
1.仅支持802.11n，希望能增加ac
2.丢包率较高25%，希望优化
3.提高下载速率

**Comment by CelestialSayuki** [comment]
itlwm只能在iwn，iwm，iwx网卡上运行，而AirPortOpenBSD是为更多网卡适配的，不仅Intel的那几个
