### ISSUE TITLE
Can't connect to Hidden Network

### ISSUE THREAD

**Issue by null2264** [a565109863/AirPortOpenBSD#6]
Everytime I try to connect to a hidden network (by clicking "Other...") it'll give me "The network could not be found." error.
It'd be really useful to have this feature since sometimes my wifi wouldn't show up on the list even tho other wifi is there, so when this happens I can just manually join to my wifi

**Comment by a565109863** [comment]
The driver cannot connect to the hidden network

**Comment by null2264** [comment]
You mean it also doesn't work on OpenBSD or you have no plan on adding support for hidden wifi?

**Comment by a565109863** [comment]
I tried to add support connection to hide ssid.
It works, but it doesn't work well

**Comment by null2264** [comment]
I see, that's unfortunate... Welp thanks for the reply tho

**Comment by a565109863** [comment]
It supports connection hidden network now

**Comment by null2264** [comment]
Awesome, thank you!
